from django.urls import path

from . import settings
from .views.index import IndexView

from .views.breeder import (
    BreederIndexView,
    BreederView,
    BreederCreateView,
    BreederDeleteView,
    BreederUpdateView,
    BreederTranslationView,
    HxBreederDeleteView,
    HxBreederFilterView,
    HxBreederTranslationView,
    HxStrainFilterView,
)

from .views.strain import (

    StrainAddToStockView,
    StrainAddToStock2View,

    StrainCommentCreateView,
    StrainCommentUpdateView,
    StrainCreateView,
    StrainDeleteView,
    StrainGalleryView,
    StrainImageUploadView,
    StrainRemoveFromStockView,
    StrainSearchView,
    StrainTranslationView,
    StrainUpdateView,
    StrainView,
    HxStrainDeleteView,
    HxStrainAddToStockView,
    HxStrainAddToStock2View,
    HxStrainRemoveFromStockView,
    HxStrainSearchView,
    HxStrainStockNotesView,
    HxStrainTranslationView,
    HxSeedsInStockInfoView,
    HxSeedsInStockDialogView,
    HxSeedsInStockDialogUpdateView,
)

from .views.location import (
     HxLocationTypeChangeView,
     LocationIndexView,
     LocationCreateView,
     LocationUpdateView,
     LocationDeleteView,
     HxLocationTypeChangeView,
     HxLocationDeleteView,
)

from .views.user import (
     UserInfoView,
     HxUserInfoAddSeedsToStockView,
     HxUserInfoRemoveSeedsFromStockView,
)

from .views.growlog import (  # noqa: F401
     GrowlogCreateView,
     GrowlogUpdateView,
     GrowlogDeleteView,
     GrowlogDetailView,
     GrowlogEntryCreateView,
     GrowlogEntryUpdateView,
     GrowlogEntryDeleteView,
     GrowlogEntryUploadImageView,
     GrowlogEntryUpdateImageView,
     GrowlogEntryDeleteImageView,
     HxGrowlogEditNotesView,
     HxGrowlogEditDescriptionView,
     HxGrowlogActiveInfoView,
     HxGrowlogFinishedInfoView,
     HxGrowlogEntriesView,
     HxGrowlogEntryCreateView,
     HxGrowlogEntryUpdateView,
     HxGrowlogEntryDeleteView,
     HxGrowlogEntryUploadImageView,
     HxGrowlogEntryDeleteImageView,
     HxGrowlogEntryUpdateImageView,
     HxGrowlogAddSeedsView,
     HxGrowlogAddStrainView,
     HxGrowlogAddStrainUpdateView,
     HxGrowlogAddPlantsView,
     HxGrowlogRemovePlantsView,
     HxGrowlogDeleteStrainView,
     GrowlogSetGerminatingAtView,
     GrowlogUnsetGerminatingAtView,
     GrowlogSetCuttedAtView,
     GrowlogUnsetCuttedAtView,
     GrowlogSetVegetativeAtView,
     GrowlogUnsetVegetativeAtView,
     GrowlogSetFloweringAtView,
     GrowlogUnsetFloweringAtView,
     GrowlogSetHarvestedAtView,
     GrowlogUnsetHarvestedAtView,
     GrowlogSetFinishedAtView,
     GrowlogUnsetFinishedAtView,
     MyGrowlogsView,
     MyStrainsGrownView,
)

from .views.utils import HxSelectDateDaysSanitizeView

app_name = "grow"

breeder_patterns = [
     # Views for creating, updating, deleting Breeders
    path("breeder/create/", BreederCreateView.as_view(), name="breeder-create"),
    path("breeder/update/<int:pk>/", BreederUpdateView.as_view(), name="breeder-update"),
    path("breeder/delete/<int:pk>/", BreederDeleteView.as_view(), name="breeder-delete"),
    path("breeder/translate/<int:pk>/",
         BreederTranslationView.as_view(),
         name="breeder-translate"),
    path("__hx__/breeder/delete/<int:pk>", HxBreederDeleteView.as_view(), name="hx-breeder-delete"),
    path("__hx__/breeder/filter-strains/<int:breeder_pk>/",
         HxStrainFilterView.as_view(),
         name="hx-strain-filter"),
    path("__hx__/breeder/translation/<int:pk>/",
         HxBreederTranslationView.as_view(),
         name="hx-breeder-translation"),

]

strain_patterns = [
    path("", IndexView.as_view(), name="home"),
    # Views for Breeders and Strains details
    path("strains/", BreederIndexView.as_view(), name="breeder-overview"),
    path("strains/<slug:slug>/", BreederView.as_view(), name="breeder-detail"),
    path("strains/<slug:breeder_slug>/<slug:slug>/", StrainView.as_view(), name="strain-detail"),


     # Views for creating, updating, deleting Strains
    path("strain/create/<int:breeder_pk>",
         StrainCreateView.as_view(),
         name="strain-create"),
    path("strain/update/<int:pk>/", StrainUpdateView.as_view(), name="strain-update"),
    path("strain/delete/<int:pk>/", StrainDeleteView.as_view(), name="strain-delete"),
    path("strain/gallery/<int:strain_pk>/",
         StrainGalleryView.as_view(),
         name="strain-gallery"),
    path("strain/image-upload/<int:strain_pk>/",
         StrainImageUploadView.as_view(),
         name="strain-image-upload"),
    path("strain/search/", StrainSearchView.as_view(), name="strain-search"),
    path("strain/translate/<int:pk>/",
         StrainTranslationView.as_view(),
         name="strain-translate"),
    path("strain/add_to_stock/<int:strain>/<int:feminized>/",
         StrainAddToStockView.as_view(),
         name="strain-add-to-stock"),
    path("strain/add_to_stock/", StrainAddToStock2View.as_view(), name="strain-add-to-stock2"),
    path("strain/remove_from_stock/<int:strain>/<int:feminized>/",
         StrainRemoveFromStockView.as_view(),
         name="strain-remove-from-stock"),
     path("strain/add_comment/<int:strain_pk>/",
         StrainCommentCreateView.as_view(),
         name="strain-comment-add"),
     path("strain/update_comment/<int:pk>/",
         StrainCommentUpdateView.as_view(),
         name="strain-comment-update"),

    # HTMX Views
    path("__hx__/sanitize_date_day/<int:year>/<int:month>/",
         HxSelectDateDaysSanitizeView.as_view(),
         name="hx-sanitize-date-day"),
    path("__hx__/strain/delete/<int:pk>", HxStrainDeleteView.as_view(), name="hx-strain-delete"),
    path("__hx__/strain/add_to_stock/<int:strain>/<int:feminized>/",
         HxStrainAddToStockView.as_view(),
         name="hx-strain-add-to-stock"),
    path("__hx__/strain/add_to_stock2/",
         HxStrainAddToStock2View.as_view(),
         name="hx-strain-add-to-stock2"),
    path("__hx__/strain/filter/<int:breeder_pk>/",
         HxStrainFilterView.as_view(),
         name="hx-strain-filter"),
    path("__hx__/strain/remove_from_stock/<int:strain>/<int:feminized>/",
         HxStrainRemoveFromStockView.as_view(),
         name="hx-strain-remove-from-stock"),
    path("__hx__/strain/stock_notes/<int:pk>/", HxStrainStockNotesView.as_view(), name="hx-strain-stock-notes"),
    path("__hx__/strain/delete/<int:pk>/", HxStrainDeleteView.as_view(), name="hx-strain-delete"),
    path("__hx__/strain/translation/<int:pk>/",
         HxStrainTranslationView.as_view(),
         name="hx-strain-translation"),
    path("__hx__/breeder/filter/",
         HxBreederFilterView.as_view(),
         name="hx-breeder-filter"),
    path("__hx__/select_date_days_sanitize/<int:year>/<int:month>/",
         HxSelectDateDaysSanitizeView.as_view(),
         name="hx-select-date-days-sanitize"),
    path("__hx__/select_date_days_sanitize/<int:year>/<int:month>/<int:day>/",
         HxSelectDateDaysSanitizeView.as_view(),
         name="hx-select-date-days-sanitize"),
    path("__hx__/strain/search/", HxStrainSearchView.as_view(), name="hx-strain-search"),
    path("__hx__/strain/seeds_in_stock_info/",
         HxSeedsInStockInfoView.as_view(),
         name="hx-seeds-in-stock-info"),
    path("__hx__/strain/seeds_in_stock_dialog/",
         HxSeedsInStockDialogView.as_view(),
         name="hx-seeds-in-stock-dialog"),
    path("__hx__/strain/seeds_in_stock_dialog/update/",
         HxSeedsInStockDialogUpdateView.as_view(),
         name="hx-seeds-in-stock-dialog-update"),
]


location_patterns = [
     path("location/", LocationIndexView.as_view(), name="location-index"),
     path("location/create/", LocationCreateView.as_view(), name="location-create"),
     path("location/update/<int:pk>/", LocationUpdateView.as_view(), name="location-update"),
     path("location/delete/<int:pk>/", LocationDeleteView.as_view(), name="location-delete"),
     #path("location/detail/<int:pk>/", LocationDetailView.as_view(), name="location-detail"),
     path("__hx__/location/type-change/<int:pk>/",
          HxLocationTypeChangeView.as_view(),
          name="hx-location-type-change"),
     path("__hx__/location/delete/<int:pk>/", HxLocationDeleteView.as_view(), name="hx-location-delete"),
]

user_patterns = [
     path("grow/my-info/", UserInfoView.as_view(), name="user-info"),
     path("__hx__/grow/user/add_seeds_to_stock/<int:strain>/<int:feminized>/",
          HxUserInfoAddSeedsToStockView.as_view(),
          name="hx-user-add-seeds-to-stock"),
     path("__hx__/grow/user/remove_seeds_from_stock/<int:strain>/<int:feminized>/",
          HxUserInfoRemoveSeedsFromStockView.as_view(),
          name="hx-user-remove-seeds-from-stock"),
]

growlog_patterns = [
     path("growlog/create/", GrowlogCreateView.as_view(), name="growlog-create"),
     path("growlog/<int:pk>/update/", GrowlogUpdateView.as_view(), name="growlog-update"),
     path("growlog/<int:pk>/delete/", GrowlogDeleteView.as_view(), name="growlog-delete"),
     path("growlog/<int:pk>/detail/", GrowlogDetailView.as_view(), name="growlog-detail"),
     path("__hx__/growlog/<int:pk>/edit_notes/",
          HxGrowlogEditNotesView.as_view(),
          name="hx-growlog-edit-notes"),
     path("__hx__/growlog/<int:growlog_pk>/add_seeds/",
          HxGrowlogAddSeedsView.as_view(),
          name="hx-growlog-seeds-add"),
     path("__hx__/growlog/<int:growlog_pk>/add_strain/",
          HxGrowlogAddStrainView.as_view(),
          name="hx-growlog-strain-add"),
     path("__hx__/growlog/<int:growlog_pk>/add_strain/update/",
          HxGrowlogAddStrainUpdateView.as_view(),
          name="hx-growlog-strain-add-update"),
     path("__hx__/growlog/<int:pk>/edit_description/",
          HxGrowlogEditDescriptionView.as_view(),
          name="hx-growlog-edit-description"),
     # path("__hx__/growlog/<int:pk>/entries/",
     #     HxGrowlogEntriesView.as_view(),
     #     name="hx-growlog-entries"),path("__hx__/growlog/add_plants/<int:pk>/",
     path("__hx__/growlog/plants/add/<int:pk>/",
          HxGrowlogAddPlantsView.as_view(),
          name="hx-growlog-plants-add"),
     path("__hx__/growlog/plants/remove/<int:pk>/",
          HxGrowlogRemovePlantsView.as_view(),
          name="hx-growlog-plants-remove"),
     path("__hx__/growlog/strain/delete/<int:pk>/",
          HxGrowlogDeleteStrainView.as_view(),
          name="hx-growlog-strain-delete"),
     path("__hx__/growlog/<int:pk>/edit_description/",
          HxGrowlogEditDescriptionView.as_view(),
          name="hx-growlog-edit-description"),
     path("__hx__/growlog/active_info/",
          HxGrowlogActiveInfoView.as_view(),
          name="hx-growlog-active-info"),
     path("__hx__/growlog/finished_info/",
          HxGrowlogFinishedInfoView.as_view(),
          name="hx-growlog-finished-info"),
     path("__hx__/growlog/<int:growlog_pk>/entry_create/",
          HxGrowlogEntryCreateView.as_view(),
          name="hx-growlog-entry-create"),
     path("__hx__/growlog/entry/update/<int:pk>/",
          HxGrowlogEntryUpdateView.as_view(),
          name="hx-growlog-entry-update"),
     path("__hx__/growlog/entry/delete/<int:pk>/",
          HxGrowlogEntryDeleteView.as_view(),
          name="hx-growlog-entry-delete"),
     path("__hx__/growlog/<int:growlog_pk>/entry/image_upload/",
          HxGrowlogEntryUploadImageView.as_view(),
          name="hx-growlog-entry-image-upload"),
     path("__hx__/growlog/entry/image/update/<int:pk>/",
          HxGrowlogEntryUpdateImageView.as_view(),
          name="hx-growlog-entry-image-update"),
     path("__hx__/growlog/entry/image/delete/<int:pk>/",
          HxGrowlogEntryDeleteImageView.as_view(),
          name="hx-growlog-entry-image-delete"),
     path("__hx__/growlog<int:growlog_pk>/entries",
          HxGrowlogEntriesView.as_view(),
          name="hx-growlog-entries"),
     path("growlog/<int:growlog_pk>/entry-create/",
          GrowlogEntryCreateView.as_view(),
          name="growlog-entry-create"),
     path("growlog/<int:pk>/set-germinating-at/",
          GrowlogSetGerminatingAtView.as_view(),
          name="growlog-set-germinating-at"),
     path("growlog/<int:pk>/unset-germinating-at/",
          GrowlogUnsetGerminatingAtView.as_view(),
          name="growlog-unset-germinating-at"),
     path("growlog/<int:pk>/set-cutted-at/",
          GrowlogSetCuttedAtView.as_view(),
          name="growlog-set-cutted-at"),
     path("growlog/<int:pk>/unset-cutted-at/",
          GrowlogUnsetCuttedAtView.as_view(),
          name="growlog-unset-cutted-at"),
     path("growlog/<int:pk>/set-vegetative-at/",
          GrowlogSetVegetativeAtView.as_view(),
          name="growlog-set-vegetative-at"),
     path("growlog/<int:pk>/unset-vegetative-at/",
          GrowlogUnsetVegetativeAtView.as_view(),
          name="growlog-unset-vegetative-at"),
     path("growlog/<int:pk>/set-flowering-at/",
          GrowlogSetFloweringAtView.as_view(),
          name="growlog-set-flowering-at"),
     path("growlog/<int:pk>/unset-flowering-at/",
          GrowlogUnsetFloweringAtView.as_view(),
          name="growlog-unset-flowering-at"),
     path("growlog/<int:pk>/set-harvested-at/",
          GrowlogSetHarvestedAtView.as_view(),
          name="growlog-set-harvested-at"),
     path("growlog/<int:pk>/unset-harvested-at/",
          GrowlogUnsetHarvestedAtView.as_view(),
          name="growlog-unset-harvested-at"),
     path("growlog/<int:pk>/set-finished-at/",
          GrowlogSetFinishedAtView.as_view(),
          name="growlog-set-finished-at"),
     path("growlog/<int:pk>/unset-finished-at/",
          GrowlogUnsetFinishedAtView.as_view(),
          name="growlog-unset-finished-at"),
     path("growlog/entry/update/<int:pk>/",
          GrowlogEntryUpdateView.as_view(),
          name="growlog-entry-update"),
     path("growlog/entry/delete/<int:pk>/",
          GrowlogEntryDeleteView.as_view(),
          name="growlog-entry-delete"),
     path("growlog/entry/<int:entry_pk>/image_upload",
          GrowlogEntryUploadImageView.as_view(),
          name="growlog-entry-image-upload"),
     path("growlog/entry/image/update/<int:pk>/",
          GrowlogEntryUpdateImageView.as_view(),
          name="growlog-entry-image-update"),
     path("growlog/entry/image/delete/<int:pk>/",
          GrowlogEntryDeleteImageView.as_view(),
          name="growlog-entry-image-delete"),
     path('my-grow/growlogs/', MyGrowlogsView.as_view(), name='my-growlogs'),
     path('my-grow/strains-grown/', MyStrainsGrownView.as_view(), name='my-strains-grown'),
]

urlpatterns = [
     *breeder_patterns,
     *strain_patterns,
     *location_patterns,
     *growlog_patterns,
     *user_patterns,
]
