FROM docker.io/library/python:3.14-slim-trixie

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_NO_INTERACTION=1
ENV DJANGO_SETTINGS_MODULE=django_project.settings
ENV GROW_DEBUG=1
ENV GROW_ALLOWED_HOSTS='*'
ENV GROW_MEDIA_ROOT=/data/media
ENV GROW_STATIC_ROOT=/data/static


RUN apt-get update && apt-get install -y --no-install-recommends \
		build-essential \
		libpq-dev \
		gettext \
		git \
		npm \
		firebird-dev \
	&& apt-get clean \
    && pip install --upgrade pip setuptools wheel \
	&& pip install poetry \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /app /data/static /data/media /data/run

VOLUME /data/media
VOLUME /data/static
VOLUME /data/run

WORKDIR /app

COPY . .
RUN poetry config virtualenvs.in-project false \
	&& poetry install --with=dev --no-interaction --no-ansi --no-root \
	&& npm install

RUN chmod +x /app/runserver.sh

ENTRYPOINT ["./runserver.sh"]

CMD ["runserver", "0.0.0.0:8000"]
