#!/bin/sh

self="$(realpath "$0")"
BASE_DIR="$(dirname "$self")"

cd "$BASE_DIR"

poetry export --format requirements.txt --output requirements/dev.txt --all-groups --without-hashes
poetry export --format requirements.txt --output requirements/prod.txt --without=firebird --without=dev

