# Generated by Django 5.2.9 on 2026-01-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='strainsinstock',
            name='strainsinstock_one_of_regular_feminized_notset',
        ),
    ]
