# Generated by Django 5.2.9 on 2026-01-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='discotinued',
            field=models.BooleanField(default=False, verbose_name='discontinued'),
        ),
    ]
