# Generated by Django 5.2.9 on 2026-01-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growroom',
            old_name='ventilation_intesity',
            new_name='ventilation_intensity',
        ),
        migrations.AlterField(
            model_name='location',
            name='description_type',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type'),
        ),
        migrations.RenameField(
            model_name='location',
            old_name='description_type',
            new_name='description_type_data',
        ),
        migrations.RemoveField(
            model_name='growroom',
            name='light_cycle_hours',
        ),
        migrations.AlterField(
            model_name='breedertranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], max_length=16, verbose_name='language code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type_data',
            field=models.CharField(choices=[('indoor', 'indoor'), ('outdoor', 'outdoor'), ('greenhouse', 'greenhouse'), ('balcony', 'balcony')], default='indoor', max_length=50, verbose_name='location type'),
        ),
        migrations.AlterField(
            model_name='straintranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], max_length=16, verbose_name='Language code'),
        ),
        migrations.AlterField(
            model_name='strainusercomment',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='de-at', max_length=16, verbose_name='language'),
        ),
    ]
