# Generated by Django 5.2.9 on 2026-01-09 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeder',
            name='breeder_url',
            field=models.URLField(blank=True, null=True, verbose_name="Breeder's Website URL"),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='description_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type'),
        ),
        migrations.AlterField(
            model_name='breedertranslation',
            name='description_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='description_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='notes_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], db_column='notes_type', default='markdown', max_length=50, verbose_name='notes type'),
        ),
        migrations.AlterField(
            model_name='growlogentry',
            name='content_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], db_column='content_type', default='markdown', max_length=50, verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='growlogentryimage',
            name='description_type',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], default='markdown', max_length=50, verbose_name='description type'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description_type',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], default='markdown', max_length=50, verbose_name='description type'),
        ),
        migrations.AlterField(
            model_name='outdoorlocation',
            name='notes_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], default='markdown', max_length=50, verbose_name='description type'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='description_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type'),
        ),
        migrations.AlterField(
            model_name='strainimage',
            name='description_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], default='markdown', max_length=50, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='strainsinstock',
            name='notes_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], db_column='notes_type', default='markdown', max_length=50, verbose_name='text type'),
        ),
        migrations.AlterField(
            model_name='straintranslation',
            name='description_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type'),
        ),
        migrations.AlterField(
            model_name='strainusercomment',
            name='comment_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode'), ('plaintext', 'plain text')], db_column='comment_type', default='markdown', max_length=50, verbose_name='description type'),
        ),
        migrations.AlterField(
            model_name='strainusercomment',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='growapi.strain', verbose_name='strain'),
        ),
    ]
