# Generated by Django 5.2.9 on 2026-01-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapi', '0002_rename_ventilation_intesity_growroom_ventilation_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outdoorlocation',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_location', to='growapi.location', verbose_name='location'),
        ),
    ]
