# Generated by Django 5.2.9 on 2026-01-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growapi', '0002_strain_discotinued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strain',
            old_name='discotinued',
            new_name='is_discontinued',
        ),
    ]
