# Generated by Django 5.2.9 on 2026-01-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growapi', '0003_alter_outdoorlocation_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outdoorlocation',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
