# Generated by Django 5.2.9 on 2026-01-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapi', '0003_rename_discotinued_strain_is_discontinued'),
    ]

    operations = [
        migrations.AddField(
            model_name='strainimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='is_discontinued',
            field=models.BooleanField(default=False, verbose_name='is discontinued'),
        ),
    ]
