# Generated by Django 5.2.9 on 2026-01-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapi', '0004_rename_logitude_outdoorlocation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outdoorlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='outdoorlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='longitude'),
        ),
    ]
