# Generated by Django 5.2.9 on 2026-02-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growapi", "0005_alter_outdoorlocation_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="growlog",
            name="slug",
        ),
    ]
