# Generated by Django 5.2.9 on 2026-02-16 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growapi", "0006_remove_growlog_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="growlog",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="personal notes"
            ),
        ),
        migrations.AlterField(
            model_name="growlog",
            name="notes_type_data",
            field=models.CharField(
                choices=[
                    ("markdown", "markdown"),
                    ("bbcode", "bbcode"),
                    ("plaintext", "plain text"),
                ],
                db_column="notes_type",
                default="markdown",
                max_length=50,
                verbose_name="personal notes type",
            ),
        ),
        migrations.CreateModel(
            name="GrowUserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "growlog_paginate",
                    models.IntegerField(default=20, verbose_name="growlog paginate"),
                ),
                ("paginate", models.IntegerField(default=25, verbose_name="paginate")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grow_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "grow setting",
                "verbose_name_plural": "grow settings",
                "db_table": "grow_user_settings",
            },
        ),
    ]
