# Generated by Django 5.2.9 on 2026-02-23 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growapi", "0007_alter_growlog_notes_alter_growlog_notes_type_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="growlog",
            options={"ordering": ["-started_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="growlog",
            unique_together={("grower", "name")},
        ),
    ]
