# Generated by Django 5.2.9 on 2026-03-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growapi", "0008_alter_growlog_options_alter_growlog_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="growlog",
            name="germinated_at",
        ),
        migrations.AddField(
            model_name="growlog",
            name="germinating_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="germinating at"
            ),
        ),
        migrations.AddField(
            model_name="growlog",
            name="vegetative_at",
            field=models.DateField(blank=True, null=True, verbose_name="vegetative at"),
        ),
    ]
