# Generated by Django 5.2.9 on 2026-03-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "growapi",
            "0009_remove_growlog_germinated_at_growlog_germinating_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="growlogentryimage",
            name="description_type",
            field=models.CharField(
                choices=[
                    ("markdown", "markdown"),
                    ("bbcode", "bbcode"),
                    ("plaintext", "plain text"),
                ],
                db_column="description_type",
                default="markdown",
                max_length=50,
                verbose_name="description type",
            ),
        ),
        migrations.RenameField(
            model_name="growlogentryimage",
            old_name="description_type",
            new_name="description_type_data",
        ),
    ]
