# Generated by Django 5.2.9 on 2026-03-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growapi", "0010_alter_growlogentryimage_description_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growroom",
            name="depth",
            field=models.PositiveIntegerField(
                blank=True,
                default=200,
                help_text="Depth in centimeters.",
                null=True,
                verbose_name="depth",
            ),
        ),
        migrations.AlterField(
            model_name="growroom",
            name="height",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Height in centimeters.",
                null=True,
                verbose_name="height",
            ),
        ),
        migrations.AlterField(
            model_name="growroom",
            name="width",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Width in centimeters.",
                null=True,
                verbose_name="width",
            ),
        ),
    ]
