# Generated by Django 5.2.9 on 2026-03-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growapi", "0011_alter_growroom_depth_alter_growroom_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="growlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
