# Generated by Django 5.2.9 on 2026-03-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growapi", "0012_growlog_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growlogentryimage",
            name="description",
            field=models.TextField(
                default="", max_length=4096, verbose_name="description"
            ),
        ),
    ]
