# Generated by Django 5.2.9 on 2026-03-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growapi", "0013_alter_growlogentryimage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="growlogentryimage",
            name="caption",
            field=models.CharField(
                blank=True,
                default="Picture of my grow",
                max_length=255,
                null=True,
                verbose_name="caption",
            ),
        ),
        migrations.AlterField(
            model_name="growlogentryimage",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                max_length=4096,
                null=True,
                verbose_name="description",
            ),
        ),
    ]
