# Generated by Django 5.2.13 on 2026-04-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growapi", "0014_growlogentryimage_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growlogentryimage",
            name="caption",
            field=models.TextField(
                blank=True,
                default="Picture of my grow",
                max_length=1024,
                null=True,
                verbose_name="caption",
            ),
        ),
        migrations.AlterField(
            model_name="strainusercomment",
            name="language_code",
            field=models.CharField(
                choices=[("en", "English"), ("de", "Deutsch")],
                default="en-us",
                max_length=16,
                verbose_name="language",
            ),
        ),
    ]
