# Generated by Django 6.0 on 2025-12-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growlog_permission_data', models.CharField(choices=[('friends_only', 'friends only'), ('members_only', 'members only'), ('private', 'private'), ('public', 'public')], default='private', max_length=50, verbose_name='Default growlog permission')),
                ('location_permission_data', models.CharField(choices=[('friends_only', 'friends only'), ('members_only', 'members only'), ('private', 'private'), ('public', 'public')], default='private', max_length=50, verbose_name='Default location permission')),
            ],
        ),
    ]
