# Generated by Django 5.2.9 on 2026-01-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growlog_permission_data', models.CharField(choices=[('friends_only', 'friends only'), ('members_only', 'members only'), ('private', 'private'), ('public', 'public')], default='private', max_length=50, verbose_name='Default growlog permission')),
                ('location_permission_data', models.CharField(choices=[('friends_only', 'friends only'), ('members_only', 'members only'), ('private', 'private'), ('public', 'public')], default='private', max_length=50, verbose_name='Default location permission')),
                ('length_unit', models.CharField(choices=[('metric', 'metric'), ('imperial', 'imperial')], default='metric', max_length=50, verbose_name='unit of length')),
                ('temperature_unit', models.CharField(choices=[('C', 'Celcius'), ('F', 'Fahrenheit'), ('K', 'Kelvin')], default='C', max_length=1)),
            ],
        ),
    ]
