# Generated by Django 5.2.9 on 2026-01-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='length_unit',
            field=models.CharField(choices=[('metric', 'metric'), ('imperial', 'imperial')], default='metric', max_length=50, verbose_name='unit of length'),
        ),
    ]
