"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from environ import Env
from django.conf import settings
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as L_, pgettext_lazy as Q_

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOCAL_SETTINGS_DIR = Path(__file__).resolve().parent / 'local'
env = Env(
    GROW_DEBUG=(bool, False),
    GROW_SECRET_KEY=(str, 'django-insecure-#zp@r)@gr(f%o3y3*g1dup_z+@lt$o)mgq#8ne%llaz4vh82lf'),
    GROW_ALLOWED_HOSTS=(list, ['*']),
    GROW_DATABASE=(str, f'sqlite:////{BASE_DIR / "db.sqlite3"}'),
    GROW_DEFAULT_FROM_EMAIL=(str, 'webmaster@localhost'),
    GROW_EMAIL_BACKEND=(str, 'django.core.mail.backends.console.EmailBackend'),
    GROW_EMAIL_HOST=(str, 'localhost'),
    GROW_EMAIL_PORT=(int, 25),
    GROW_EMAIL_USE_TLS=(bool, False),
    GROW_EMAIL_HOST_USER=(str, ''),
    GROW_EMAIL_HOST_PASSWORD=(str, ''),
    GROW_STATIC_URL=(str, 'static/'),
    GROW_STATIC_ROOT=(str, BASE_DIR / '.static'),
    GROW_MEDIA_URL=(str, 'media/'),
    GROW_MEDIA_ROOT=(str, BASE_DIR / '.media'),
    GROW_TIME_ZONE=(str, 'UTC'),
    GROW_LANGUAGE_CODE=(str, 'en-us'),
    GROW_ALLOW_SIGNUP=(bool, True),
    GROW_ADMIN_URL=(str, "admin/"),
    GROW_ACCOUNT_LOGIN_METHODS=(list, ['email']),
    GROW_LOGIN_REQUIRED=(bool, False),
    GROW_INCLUDE_WIKI=(bool, True)
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('GROW_DEBUG')

if (BASE_DIR / '.env').is_file():
    env.read_env(BASE_DIR / '.env')
if (LOCAL_SETTINGS_DIR / '.env').exists():
    env.read_env(LOCAL_SETTINGS_DIR / '.env')


if DEBUG and (BASE_DIR / '.env-dev').is_file():
    env.read_env(BASE_DIR / '.env-dev')
elif not DEBUG and (BASE_DIR / '.env-prod').is_file():
    env.read_env(BASE_DIR / '.env-prod')

# HERE for docker includes
if DEBUG and (LOCAL_SETTINGS_DIR / '.env-dev').is_file():
    env.read_env(LOCAL_SETTINGS_DIR / '.env-dev')
elif not DEBUG and (LOCAL_SETTINGS_DIR / 'local' / '.env-prod').is_file():
    env.read_env(LOCAL_SETTINGS_DIR / 'local' / '.env-prod')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('GROW_SECRET_KEY')
if (LOCAL_SETTINGS_DIR / 'secret_key').is_file():
    with open(LOCAL_SETTINGS_DIR / 'secret_key', 'rt', encoding='utf-8') as skf:
        SECRET_KEY = skf.readline().strip()

if (LOCAL_SETTINGS_DIR / 'secret_key_fallabcks').is_file():
    with open(LOCAL_SETTINGS_DIR / 'secret_key_fallbacks', 'rt', encoding='utf-8') as skf:
        SECRET_KEY_FALLBACKS = [
            line.strip() for line in skf.readlines() if line.strip()
        ]

ALLOWED_HOSTS = env('GROW_ALLOWED_HOSTS')


# Application definition

django_apps = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

third_party_apps = [
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.openid',
    'allauth.socialaccount.providers.steam',
    'rest_framework',
    'widget_tweaks',
]

project_apps = [
    'core',
    'grow',
    'grow.api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.core',
                'grow.context_processors.grow',
            ],
        },
    },
]
BASE_TEMPLATE = "base.html"

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('GROW_DATABASE'),
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = env('GROW_LANGUAGE_CODE')
LANGUAGES = [
    ('en-us', 'English (US)'),
    ('de', 'Deutsch'),
]
TIME_ZONE = env('GROW_TIME_ZONE')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / 'staticfiles',
]
STATIC_URL = env('GROW_STATIC_URL')
STATIC_ROOT = env('GROW_STATIC_ROOT')
MEDIA_URL = env('GROW_MEDIA_URL')
MEDIA_ROOT = env('GROW_MEDIA_ROOT')

AUTH_USER_MODEL = 'core.User'

EMAIL_BACKEND = env('GROW_EMAIL_BACKEND')
DEFAULT_FROM_EMAIL = env('GROW_DEFAULT_FROM_EMAIL')
EMAIL_HOST = env('GROW_EMAIL_HOST')
EMAIL_PORT = env('GROW_EMAIL_PORT')
EMAIL_USE_TLS = env('GROW_EMAIL_USE_TLS')
EMAIL_HOST_USER = env('GROW_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('GROW_EMAIL_HOST_PASSWORD')

# Allauth settings
ACCOUNT_SIGNUP_FIELDS = [
    'username*',
    'email*',
    'first_name',
    'last_name',
    'password1*',
    'password2*',
]
ACCOUNT_SIGNUP_FORM_HONEYPOT_FIELD = 'country'
ACCOUNT_LOGIN_METHODS = env('GROW_ACCOUNT_LOGIN_METHODS')
ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_RESEND = True

LOGIN_REDIRECT_URL = reverse_lazy("grow:home")
LOGOUT_REDIRECT_URL = reverse_lazy("grow:home")

# PROJECT settings
ADMIN_URL = env("GROW_ADMIN_URL")
USE_BOOTSTRAP = True
ALLOW_SIGNUP = env.bool('GROW_ALLOW_SIGNUP')
LOGIN_REQUIRED = env.bool('GROW_LOGIN_REQUIRED')
INCLUDE_WIKI = env.bool('GROW_INCLUDE_WIKI')

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

if INCLUDE_WIKI:
    third_party_apps.append('tinywiki')
    TINYWIKI_HOME = Q_("wiki", "grow-home")

# load local config
_local_settings_path = BASE_DIR / 'django_project' / 'local'

if (_local_settings_path / 'settings.py').exists():
    from .local.settings import *  # noqa
if settings.DEBUG:
    if (_local_settings_path / 'settings_dev.py').exists():
        from .local.settings_dev import *  # noqa
else:
    if (_local_settings_path / 'settings_prod.py').exists():
        from .local.settings_prod import *  # noqa

del _local_settings_path

if DEBUG:
    third_party_apps.insert(0, 'django_browser_reload')
    MIDDLEWARE.insert(0, "django_browser_reload.middleware.BrowserReloadMiddleware")
    INSTALLED_APPS = list(set(django_apps + third_party_apps + project_apps))
else:
    INSTALLED_APPS = list(set(django_apps + third_party_apps + project_apps))
