"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from environ import Env
import os
from django.conf import settings
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as L_

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOCAL_SETTINGS_DIR = Path(__file__).resolve().parent / 'local'
env = Env(
    DEBUG=(bool, bool(os.environ.get('GROW_DEBUG', "0"))),
    SECRET_KEY=(str, 'django-insecure-#zp@r)@gr(f%o3y3*g1dup_z+@lt$o)mgq#8ne%llaz4vh82lf'),
    ALLOWED_HOSTS=(list, ['*']),
    DATABASE_URL=(str, f'sqlite:////{BASE_DIR / "db.sqlite3"}'),
    DEFAULT_FROM_EMAIL=(str, 'webmaster@localhost'),
    EMAIL_BACKEND=(str, 'django.core.mail.backends.console.EmailBackend'),
    EMAIL_HOST=(str, 'localhost'),
    EMAIL_PORT=(int, 25),
    EMAIL_USE_TLS=(bool, False),
    EMAIL_HOST_USER=(str, ''),
    EMAIL_HOST_PASSWORD=(str, ''),
    STATIC_URL=(str, 'static/'),
    STATIC_ROOT=(str, BASE_DIR / '.static'),
    MEDIA_URL=(str, 'media/'),
    MEDIA_ROOT=(str, BASE_DIR / '.media'),
    TIME_ZONE=(str, 'UTC'),
    LANGUAGE_CODE=(str, 'en-us'),
    ALLOW_SIGNUP=(bool, True),
    ADMIN_URL=(str, "admin/"),
    ACCOUNT_LOGIN_METHODS=(list, ['email']),
    LOGIN_REQUIRED=(bool, False),
    INCLUDE_WIKI=(bool, True),
    HEAD_TITLE=(str, 'Grow'),
    SITE_TITLE=(str, 'Grow'),
    COOKIES_CONSENT_REQUIRED=(bool, False),
    COOKIES_CONSENT_NAME=(str, 'cookies_consent'),
    AGE_GATE_REQUIRED=(bool, False),
    AGE_GATE_NAME=(str, 'age_gate_passed'),
    AGE_GATE_MINIMUM_AGE=(int, 18),
    AGE_GATE_REJECTED_URL=(str, '/age-gate/'),
    SESSION_COOKIE_NAME=(str, 'grow_sessionid'),
)

# SECURITY WARNING: don't run with debug turned on in production!


if (BASE_DIR / '.env').is_file():
    env.read_env(BASE_DIR / '.env')
if (LOCAL_SETTINGS_DIR / '.env').exists():
    env.read_env(LOCAL_SETTINGS_DIR / '.env')

DEBUG = env.bool('DEBUG')

if DEBUG and (BASE_DIR / '.env-dev').is_file():
    env.read_env(BASE_DIR / '.env-dev')
elif not DEBUG and (BASE_DIR / '.env-prod').is_file():
    env.read_env(BASE_DIR / '.env-prod')

# HERE for docker includes
if DEBUG and (LOCAL_SETTINGS_DIR / '.env-dev').is_file():
    env.read_env(LOCAL_SETTINGS_DIR / '.env-dev')
elif not DEBUG and (LOCAL_SETTINGS_DIR / 'local' / '.env-prod').is_file():
    env.read_env(LOCAL_SETTINGS_DIR / 'local' / '.env-prod')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('GROW_SECRET_KEY', default=env('SECRET_KEY'))
if (LOCAL_SETTINGS_DIR / 'secret_key').is_file():
    with open(LOCAL_SETTINGS_DIR / 'secret_key', 'rt', encoding='utf-8') as skf:
        SECRET_KEY = skf.readline().strip()

if (LOCAL_SETTINGS_DIR / 'secret_key_fallabcks').is_file():
    with open(LOCAL_SETTINGS_DIR / 'secret_key_fallbacks', 'rt', encoding='utf-8') as skf:
        SECRET_KEY_FALLBACKS = [
            line.strip() for line in skf.readlines() if line.strip()
        ]

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

django_apps = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

third_party_apps = [
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.openid',
    'allauth.socialaccount.providers.steam',
    'rest_framework',
    'widget_tweaks',
]

project_apps = [
    'core',
    'grow',
    'grow.growapi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.core',
                'grow.context_processors.grow',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db_url('DATABASE_URL'),
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = env('LANGUAGE_CODE')
LANGUAGES = [
    ('en', 'English'),
    ('de', 'Deutsch'),
]
TIME_ZONE = env('TIME_ZONE')

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / 'staticfiles',
]
STATIC_URL = env('GROW_STATIC_URL', default=env('STATIC_URL'))
STATIC_ROOT = env('GROW_STATIC_ROOT', default=env('STATIC_ROOT'))
MEDIA_URL = env('GROW_MEDIA_URL', default=env('MEDIA_URL'))
MEDIA_ROOT = env('GROW_MEDIA_ROOT', default=env('MEDIA_ROOT'))

AUTH_USER_MODEL = 'core.User'

EMAIL_BACKEND = env('GROW_EMAIL_BACKEND', default=env('EMAIL_BACKEND'))
DEFAULT_FROM_EMAIL = env('GROW_DEFAULT_FROM_EMAIL', default=env('DEFAULT_FROM_EMAIL'))
EMAIL_HOST = env('GROW_EMAIL_HOST', default=env('EMAIL_HOST'))
EMAIL_PORT = env('GROW_EMAIL_PORT', default=env('EMAIL_PORT'))
EMAIL_USE_TLS = env('GROW_EMAIL_USE_TLS', default=env('EMAIL_USE_TLS'))
EMAIL_HOST_USER = env('GROW_EMAIL_HOST_USER', default=env('EMAIL_HOST_USER'))
EMAIL_HOST_PASSWORD = env('GROW_EMAIL_HOST_PASSWORD', default=env('EMAIL_HOST_PASSWORD'))

# Allauth settings
ACCOUNT_SIGNUP_FIELDS = [
    'username*',
    'email*',
    'first_name',
    'last_name',
    'password1*',
    'password2*',
]
ACCOUNT_SIGNUP_FORM_HONEYPOT_FIELD = 'country'
ACCOUNT_LOGIN_METHODS = env('GROW_ACCOUNT_LOGIN_METHODS', default=env('ACCOUNT_LOGIN_METHODS'))
ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_RESEND = True

LOGIN_REDIRECT_URL = reverse_lazy("grow:home")
LOGOUT_REDIRECT_URL = reverse_lazy("grow:home")

# PROJECT settings
ADMIN_URL = env("GROW_ADMIN_URL", default=env("ADMIN_URL", default="admin/"))
USE_BOOTSTRAP = True
ALLOW_SIGNUP = env.bool('GROW_ALLOW_SIGNUP', default=env.bool('ALLOW_SIGNUP'))
LOGIN_REQUIRED = env.bool('GROW_LOGIN_REQUIRED', default=env.bool('LOGIN_REQUIRED'))
INCLUDE_WIKI = env.bool('GROW_INCLUDE_WIKI', default=env.bool('INCLUDE_WIKI'))

LOCALE_PATHS = [
    BASE_DIR / "locale",
    BASE_DIR / "django_project" / "locale",
]

if INCLUDE_WIKI:
    third_party_apps.append('tinywiki')
    TINYWIKI_HOME = L_("grow-home")
    TINYWIKI_BBCODE_EXTRA_FORMATTERS = [
        (
            ('breeder', 'grow.growapi.parser.bbcode.text_formatters.render_breeder_link'),
            {'standalone': True}
        ),
        (
            ('strain', 'grow.growapi.parser.bbcode.text_formatters.render_strain_link'),
            {'standalone': True}
        ),
    ]
    TINYWIKI_BBCODE_EXTRA_SIMPLE_FORMATTERS = []
    TINYWIKI_BRAND_NAME = "Grow: Wiki"

GROW_IS_MAIN_APP = True
HEAD_TITLE = env('GROW_HEAD_TITLE', default=env('HEAD_TITLE'))
SITE_TITLE = env('GROW_SITE_TITLE', default=env('SITE_TITLE'))

SITE_TITLE = "Grow"

AGE_GATE_REQUIRED = env.bool('GROW_AGE_GATE_REQUIRED', default=env.bool('AGE_GATE_REQUIRED'))
AGE_GATE_NAME = env('GROW_AGE_GATE_NAME', default=env('AGE_GATE_NAME'))
AGE_GATE_MINIMUM_AGE = env.int('GROW_AGE_GATE_MINIMUM_AGE', default=env.int('AGE_GATE_MINIMUM_AGE'))
AGE_GATE_REJECTED_URL = env('GROW_AGE_GATE_REJECTED_URL', default=env('AGE_GATE_REJECTED_URL'))
COOKIES_CONSENT_REQUIRED = env.bool('GROW_COOKIES_CONSENT_REQUIRED', default=env.bool('COOKIES_CONSENT_REQUIRED'))
COOKIES_CONSENT_NAME = env('GROW_COOKIES_CONSENT_NAME', default=env('COOKIES_CONSENT_NAME'))
SESSION_COOKIE_NAME = env('GROW_SESSION_COOKIE_NAME', default=env('SESSION_COOKIE_NAME'))
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# load local config
_local_settings_path = BASE_DIR / 'django_project' / 'local'

if (_local_settings_path / 'settings.py').exists():
    from .local.settings import *  # noqa
if settings.DEBUG:
    if (_local_settings_path / 'settings_dev.py').exists():
        from .local.settings_dev import *  # noqa
else:
    if (_local_settings_path / 'settings_prod.py').exists():
        from .local.settings_prod import *  # noqa

del _local_settings_path

if USE_BOOTSTRAP:
    BASE_TEMPLATE = "grow/bs_base.html"
else:
    BASE_TEMPLATE = "grow/base.html"

if DEBUG:
    third_party_apps.insert(0, 'django_browser_reload')
    MIDDLEWARE.insert(0, "django_browser_reload.middleware.BrowserReloadMiddleware")

INSTALLED_APPS = list(set(django_apps + third_party_apps + project_apps))
