# Generated by Django 5.2.9 on 2026-01-01 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReadingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('readings_data', models.BinaryField(db_column='readings', verbose_name='The readings')),
                ('_readings_comrepssed', models.BooleanField(db_column='readings_compressed', default=False, verbose_name='Compressed readings')),
            ],
        ),
        migrations.CreateModel(
            name='Breeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_type_data', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='logo URL')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='grow/breeder_logos/', verbose_name='logo image')),
                ('seedfinder_url', models.URLField(blank=True, null=True, verbose_name='Seedfinder URL')),
                ('breeder_url', models.URLField(blank=True, null=True, verbose_name='breeder url')),
                ('creator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeders', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='breeder moderator')),
            ],
            options={
                'db_table': 'grow_breeder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Growlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=255, verbose_name='key')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('description_type_data', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('notes_type_data', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], db_column='notes_type', default='markdown', max_length=50, verbose_name='notes type')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('germinated_at', models.DateField(blank=True, null=True, verbose_name='germinated at')),
                ('cutted_at', models.DateField(blank=True, null=True, verbose_name='Cutted at')),
                ('flowering_at', models.DateField(blank=True, null=True, verbose_name='flowering at')),
                ('harvested_at', models.DateField(blank=True, null=True, verbose_name='harvested at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('permission_data', models.CharField(choices=[('friends_only', 'friends only'), ('members_only', 'members only'), ('private', 'private'), ('public', 'public')], db_column='permission', default='private', max_length=50, verbose_name='permission')),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growlogs', to=settings.AUTH_USER_MODEL, verbose_name='grower')),
            ],
            options={
                'db_table': 'grow_growlog',
                'unique_together': {('grower', 'key')},
            },
        ),
        migrations.CreateModel(
            name='GrowlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('content', models.TextField(verbose_name='content')),
                ('content_type_data', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], db_column='content_type', default='markdown', max_length=50, verbose_name='content type')),
                ('growlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.growlog', verbose_name='grow log')),
            ],
            options={
                'db_table': 'grow_growlogentry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GrowlogEntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='grow/growlog/entry_images/', verbose_name='image')),
                ('description', models.CharField(default='', max_length=255, verbose_name='description')),
                ('description_type', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], default='markdown', max_length=50, verbose_name='description type')),
                ('is_plant_image', models.BooleanField(default=True, verbose_name='is plant image')),
                ('growlog_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.growlogentry', verbose_name='growlog entry')),
            ],
            options={
                'db_table': 'grow_growlogentry_image',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=255, verbose_name='key')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('location_type_data', models.CharField(choices=[('indoor', 'indoor'), ('outdoor', 'outdoor'), ('greenhouse', 'greenhouse'), ('balcony', 'balcony')], default='indoor', editable=False, max_length=50, verbose_name='location type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_type', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], default='markdown', max_length=50, verbose_name='description type')),
                ('permission_data', models.CharField(choices=[('friends_only', 'friends only'), ('members_only', 'members only'), ('private', 'private'), ('public', 'public')], db_column='permission', default='members_only', help_text='This defines who can view the location details. If not permitted to view details only the location type is shown.', max_length=50, verbose_name='Permission')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'db_table': 'grow_location',
                'unique_together': {('owner', 'key')},
            },
        ),
        migrations.CreateModel(
            name='GrowRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_type_data', models.CharField(choices=[('led', 'led'), ('hps', 'High Pressure Sodium'), ('mh', 'Metal Halide'), ('fluorescent', 'fluorescent')], default='led', max_length=255, verbose_name='lighting')),
                ('light_cycle_hours', models.PositiveIntegerField(default=12, help_text='Number of hours the light is on during a 24-hour period.', verbose_name='light cycle hours')),
                ('light_intensity', models.PositiveIntegerField(default=0, help_text='Light intensity in lumens.', verbose_name='light intensity')),
                ('light_power_consumption', models.PositiveIntegerField(default=0, help_text='Power consumption in Watts.', verbose_name='light power consumption')),
                ('ventilation_intesity', models.PositiveIntegerField(default=0, help_text='Ventilation intensity in cubic meters per hour.', verbose_name='ventilation intensity')),
                ('ventilation_power_consumption', models.PositiveIntegerField(default=0, help_text='Power consumption in Watts.', verbose_name='ventilation power consumption')),
                ('width', models.PositiveIntegerField(default=120, help_text='Width in centimeters.', verbose_name='width')),
                ('height', models.PositiveIntegerField(default=120, help_text='Height in centimeters.', verbose_name='height')),
                ('depth', models.PositiveIntegerField(default=200, help_text='Depth in centimeters.', verbose_name='depth')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grow_room', to='api.location', verbose_name='location')),
            ],
            options={
                'db_table': 'grow_growroom',
            },
        ),
        migrations.AddField(
            model_name='growlogentry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growlog_entries', to='api.location', verbose_name='location'),
        ),
        migrations.CreateModel(
            name='OutdoorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='latitude')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='description')),
                ('notes_type_data', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], default='markdown', max_length=50, verbose_name='description type')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_locations', to='api.location', verbose_name='location')),
            ],
            options={
                'db_table': 'grow_outdoorlocation',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=255, verbose_name='key')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('sensor_type_data', models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity'), ('soil_moisture', 'soil moisture'), ('light_intensity', 'light intensity'), ('co2_level', 'CO2 level'), ('ph', 'pH'), ('ec', 'electrical conductivity'), ('temperature_medium', 'medium temperature')], db_column='sensor_type', max_length=50, verbose_name='sensor type')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.location', verbose_name='location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grow_sensor',
                'unique_together': {('owner', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='value')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.sensor', verbose_name='readings')),
            ],
            options={
                'db_table': 'grow_sensor_reading',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, verbose_name='key')),
                ('name', models.CharField(max_length=255, verbose_name='strain name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_type_data', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='logo URL')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='grow/strain/logos/', verbose_name='logo image')),
                ('strain_url', models.URLField(blank=True, null=True, verbose_name='strain homepage')),
                ('seedfinder_url', models.URLField(blank=True, null=True, verbose_name='seedfinder url')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='is automatic')),
                ('is_feminized', models.BooleanField(default=True, verbose_name='is feminized')),
                ('is_regular', models.BooleanField(default=False, verbose_name='is regular')),
                ('flowering_time_days', models.IntegerField(default=0, verbose_name='flowering time (days)')),
                ('genetics_data', models.CharField(choices=[('unknown', 'unknown'), ('indica', 'indica'), ('sativa', 'sativa'), ('ruderalis', 'ruderalis'), ('indica_ruderalis', 'indica/ruderalis hybrid'), ('sativa_ruderalis', 'sativa/ruderalis hybrid'), ('mostly_indica', 'mostly indica'), ('mostly_sativa', 'mostly sativa'), ('hybrid', 'indica/sativa hybrid'), ('hybrid_ruderalis', 'indica/sativa/ruderalis hybrid')], db_column='genetics', default='unknown', max_length=127, verbose_name='strain type')),
                ('creator_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='The name of the creator')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('breeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strains', to='api.breeder', verbose_name='breeder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strains', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'db_table': 'grow_strain',
                'ordering': ['breeder__name', 'name'],
                'unique_together': {('slug', 'breeder')},
            },
        ),
        migrations.CreateModel(
            name='StrainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='grow/strain/user_images/', verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('uplaoder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='uploader')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_type_data', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], default='markdown', max_length=50, verbose_name='description')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.strain', verbose_name='user description')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='strain_images', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'grow_strain_image',
            },
        ),
        migrations.CreateModel(
            name='BreederTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en-us', 'English (US)'), ('de', 'Deutsch')], max_length=16, verbose_name='language code')),
                ('description_type_data', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type')),
                ('description', models.TextField(verbose_name='Description')),
                ('breeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.breeder')),
            ],
            options={
                'db_table': 'grow_breeder_translation',
                'unique_together': {('language_code', 'breeder')},
            },
        ),
        migrations.CreateModel(
            name='GrowlogStrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_grown_from_seed', models.BooleanField(default=True, verbose_name='grown from seed')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('growlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growlog_strains', to='api.growlog', verbose_name='growlog')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growlog_strains', to='api.strain', verbose_name='strain')),
            ],
            options={
                'db_table': 'grow_growlog_strains',
                'unique_together': {('growlog', 'strain')},
            },
        ),
        migrations.CreateModel(
            name='StrainsInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_regular', models.BooleanField(default=False, verbose_name='regular seeds')),
                ('is_feminized', models.BooleanField(default=True, verbose_name='feminized seeds')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('bought_at', models.DateField(blank=True, null=True, verbose_name='bought at')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('notes_type_data', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], db_column='notes_type', default='markdown', max_length=50, verbose_name='text type')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.strain', verbose_name='strain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strains_in_stock', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'grow_strains_in_stock',
                'constraints': [models.CheckConstraint(condition=models.Q(('is_regular', True), ('is_feminized', True), _connector='OR'), name='strainsinstock_one_of_regular_feminized_set'), models.CheckConstraint(condition=models.Q(('is_regular', False), ('is_feminized', True), _connector='OR'), name='strainsinstock_one_of_regular_feminized_notset')],
                'unique_together': {('strain', 'user', 'is_feminized')},
            },
        ),
        migrations.CreateModel(
            name='StrainUserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField()),
                ('comment', models.TextField(verbose_name='comment')),
                ('comment_type_data', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], db_column='comment_type', default='markdown', max_length=50, verbose_name='description type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='api.strain', verbose_name='strain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strain_comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'grow_strain_user_comment',
                'unique_together': {('strain', 'user')},
            },
        ),
    ]
