# Generated by Django 5.2.9 on 2025-12-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breeder',
            old_name='key',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='strain',
            name='name',
            field=models.CharField(max_length=255, verbose_name='breeder name'),
        ),
    ]
