# Generated by Django 5.2.9 on 2025-12-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    @staticmethod
    def import_grow_data(apps, schema_editor):
        from pathlib import Path
        from grow.api.utils import import_data
        data_file = Path(__file__).resolve().parent / 'grow.zip'
        if data_file.exists():
            import_data(data_file)

    @staticmethod
    def remove_grow_data(apps, schema_editor):
        pass

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_grow_data, remove_grow_data)
    ]
