# Generated by Django 5.2.9 on 2026-01-01 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrainTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en-us', 'English (US)'), ('de', 'Deutsch')], max_length=16, verbose_name='Language code')),
                ('description_type_data', models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type')),
                ('description', models.TextField(verbose_name='description')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.strain', verbose_name='strain')),
            ],
            options={
                'db_table': 'grow_strain_translation',
                'unique_together': {('language_code', 'strain')},
            },
        ),
    ]
