# Generated by Django 5.2.9 on 2025-12-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='description_type_data',
            field=models.CharField(choices=[('markdown', 'markdown'), ('bbcode', 'bbcode')], db_column='description_type', default='markdown', max_length=50, verbose_name='description type'),
        ),
    ]
