# Generated by Django 5.2.9 on 2025-12-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_strain_description_type_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growlogentry',
            old_name='grow_log',
            new_name='growlog',
        ),
        migrations.RenameField(
            model_name='growlogstrain',
            old_name='grow_log',
            new_name='growlog',
        ),
        migrations.AlterUniqueTogether(
            name='growlogstrain',
            unique_together={('growlog', 'strain')},
        ),
    ]
