# Generated by Django 5.2.9 on 2025-12-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_key_breeder_slug_alter_strain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strain',
            old_name='key',
            new_name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='strain',
            unique_together={('slug', 'breeder')},
        ),
    ]
