# Generated by Django 5.2.9 on 2025-12-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_key_strain_slug_alter_strain_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='is_regular',
            field=models.BooleanField(default=False, verbose_name='is regular'),
        ),
    ]
